version: "2"
services:
  v2ray-client:  # v2ary客户端
    image: v2fly/v2fly-core:v4.22.0
    volumes:
    - "./config/:/etc/v2ray/"
    expose:
      - 1088  # http代理
      - 1080  # 1080 scoket5代理
    ports:
      - "8888:1088" #开http代理
    restart: always