version: "3"
services:
  v2ray-client:  # v2ary服务端
    image: v2fly/v2fly-core:v4.22.0
    volumes:
      - "./config/:/etc/v2ray/"
    expose:
      - 443
    ports:
      - "22:443"
    restart: always
